//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChronicDesease
    {
        public ChronicDesease()
        {
            this.PatientChronicDeseases = new HashSet<PatientChronicDesease>();
        }
    
        public int ChronicDeseaseId { get; set; }
        public string Name { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<PatientChronicDesease> PatientChronicDeseases { get; set; }
    }
}
