//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalExamination
    {
        public ClinicalExamination()
        {
            this.PatientClinicalExaminations = new HashSet<PatientClinicalExamination>();
        }
    
        public int ClinicalExaminationId { get; set; }
        public string Name { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<PatientClinicalExamination> PatientClinicalExaminations { get; set; }
    }
}
