//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalNote
    {
        public MedicalNote()
        {
            this.PatientMedicalNotes = new HashSet<PatientMedicalNote>();
        }
    
        public int MedicalNoteId { get; set; }
        public string Name { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<PatientMedicalNote> PatientMedicalNotes { get; set; }
    }
}
