//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastMedicalHistory
    {
        public PastMedicalHistory()
        {
            this.PatientPastMedicalHistories = new HashSet<PatientPastMedicalHistory>();
        }
    
        public int PastMedicalHistoryId { get; set; }
        public string Name { get; set; }
        public int SortKey { get; set; }
    
        public virtual ICollection<PatientPastMedicalHistory> PatientPastMedicalHistories { get; set; }
    }
}
