//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientChronicDeseases = new HashSet<PatientChronicDesease>();
            this.PatientConsultations = new HashSet<PatientConsultation>();
            this.PatientConsultationSickNotes = new HashSet<PatientConsultationSickNote>();
            this.PatientDeseaseScreenings = new HashSet<PatientDeseaseScreening>();
            this.PatientMedicalAidDependancies = new HashSet<PatientMedicalAidDependancy>();
            this.PatientPastMedicalHistories = new HashSet<PatientPastMedicalHistory>();
        }
    
        public int PatientId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string EthnicGroup { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string IDNumber { get; set; }
        public string MobileNumber { get; set; }
        public string HomeTelephoneCode { get; set; }
        public string HomeTelephoneNumber { get; set; }
        public string WorkTelephoneCode { get; set; }
        public string WorkTelephoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string MaritalStatus { get; set; }
        public string MarriageType { get; set; }
        public string PrefferedContactType { get; set; }
        public Nullable<int> PhysicalAddressId { get; set; }
        public Nullable<int> PostalAddressId { get; set; }
        public string MedicalAidName { get; set; }
        public string MedicalAidScheme { get; set; }
        public string MedicalAidNumber { get; set; }
        public Nullable<bool> PrincipalMemberInd { get; set; }
        public string PrefferedContactMethod { get; set; }
        public string SourceOfDiscovery { get; set; }
        public Nullable<bool> MedicalAidInd { get; set; }
        public string IDType { get; set; }
    
        public virtual PatientAddress PhysicalAddress { get; set; }
        public virtual PatientAddress PostalAddress { get; set; }
        public virtual ICollection<PatientChronicDesease> PatientChronicDeseases { get; set; }
        public virtual ICollection<PatientConsultation> PatientConsultations { get; set; }
        public virtual ICollection<PatientConsultationSickNote> PatientConsultationSickNotes { get; set; }
        public virtual ICollection<PatientDeseaseScreening> PatientDeseaseScreenings { get; set; }
        public virtual ICollection<PatientMedicalAidDependancy> PatientMedicalAidDependancies { get; set; }
        public virtual ICollection<PatientPastMedicalHistory> PatientPastMedicalHistories { get; set; }
    }
}
