//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientChronicDesease
    {
        public int PatientChronicDeseaseId { get; set; }
        public int PatientId { get; set; }
        public int ChronicDeseaseId { get; set; }
        public Nullable<int> YearOfDiagnoses { get; set; }
        public string Value { get; set; }
    
        public virtual ChronicDesease ChronicDesease { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
