//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVitalSign
    {
        public int PatientVitalSignId { get; set; }
        public int PatientConsultationId { get; set; }
        public int VitalSignId { get; set; }
        public string VitalSignValue { get; set; }
    
        public virtual PatientConsultation PatientConsultation { get; set; }
        public virtual VitalSign VitalSign { get; set; }
    }
}
