//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDeseaseScreening
    {
        public int PatientDeseaseScreeningId { get; set; }
        public int PatientId { get; set; }
        public int DeseaseScreeningId { get; set; }
        public Nullable<int> YearOfScreening { get; set; }
        public string Value { get; set; }
    
        public virtual DeseaseScreening DeseaseScreening { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
