//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientConsultationSickNote
    {
        public int PatientConsultationSickNoteId { get; set; }
        public int PatientConsultationId { get; set; }
        public int PatientId { get; set; }
        public string SicknessReason { get; set; }
        public string Diagnoses { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual PatientConsultation PatientConsultation { get; set; }
    }
}
