//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAddress
    {
        public PatientAddress()
        {
            this.Patients = new HashSet<Patient>();
            this.Patients1 = new HashSet<Patient>();
        }
    
        public int PatientAddressId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Patient> Patients1 { get; set; }
    }
}
