//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUserRole
    {
        public int SecurityUserRoleId { get; set; }
        public int SecurityUserId { get; set; }
        public int SecurityRoleId { get; set; }
    
        public virtual SecurityRole SecurityRole { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
