//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public SecurityUser()
        {
            this.Doctors = new HashSet<Doctor>();
            this.SecurityUserConnectionManagers = new HashSet<SecurityUserConnectionManager>();
            this.SecurityUserRoles = new HashSet<SecurityUserRole>();
        }
    
        public int SecurityUserId { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string Initials { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string WorkTelephoneCode { get; set; }
        public string WorkTelephoneNumber { get; set; }
        public string FaxCode { get; set; }
        public string FaxNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public byte[] PasswordSalt { get; set; }
        public byte[] Password { get; set; }
        public bool FirstTimeLogInInd { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<SecurityUserConnectionManager> SecurityUserConnectionManagers { get; set; }
        public virtual ICollection<SecurityUserRole> SecurityUserRoles { get; set; }
    }
}
