//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMenuItem
    {
        public int SecurityMenuItemId { get; set; }
        public int SecurityObjectId { get; set; }
        public string MenuItem { get; set; }
        public string MenuPath { get; set; }
        public int MenuOrder { get; set; }
        public string MenuType { get; set; }
    
        public virtual SecurityObject SecurityObject { get; set; }
    }
}
