//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityObjectRight
    {
        public int SecurityObjectRightId { get; set; }
        public int SecurityObjectId { get; set; }
        public string AccessType { get; set; }
        public int SecurityRoleId { get; set; }
    
        public virtual SecurityObject SecurityObject { get; set; }
        public virtual SecurityRole SecurityRole { get; set; }
    }
}
