//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSign
    {
        public VitalSign()
        {
            this.PatientVitalSigns = new HashSet<PatientVitalSign>();
        }
    
        public int VitalSignId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SortKey { get; set; }
    
        public virtual ICollection<PatientVitalSign> PatientVitalSigns { get; set; }
    }
}
